### ISSUE TITLE
ArgumentError: consul_service[consul] 

### ISSUE THREAD

**Issue by fortman** [johnbellone/consul-cookbook#428]
Environment: win2012r2
Chef Version: 12.19.36
depends 'consul', '~> 2.3.0'

Not sure what else is needed, but recipes work fine on Ubuntu 16, but when I test with Windows 2012r2, I get the following error:
```
Generated at 2017-05-03 12:54:48 -0700
ArgumentError: consul_service[consul] (consul::default line 53) had an error: ArgumentError: wrong number of arguments (given 1, expected 0)
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb:35:in `block (2 levels) in action_enable'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_builder.rb:76:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_builder.rb:76:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/dsl/resources.rb:39:in `nssm'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb:32:in `block in action_enable'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `instance_eval'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/subcontext_block.rb:54:in `subcontext_block'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:67:in `notifying_block'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/consul/libraries/consul_service_windows.rb:21:in `action_enable'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
```

**Comment by legal90** [comment]
Hi @fortman 
This issue was recently fixed by https://github.com/johnbellone/consul-cookbook/pull/422
I'll manage to release a new cookbook version with that fix soon.
At the moment I can recommend you to try the latest revision from repo's "master" branch.

**Comment by pjjohnstone** [comment]
Hi, I've pulled the latest changes from master and I still see this issue.  Running chef 12.19.36:

           ArgumentError
           -------------
           wrong number of arguments (given 1, expected 0)
